"""Scanner checks — all built-in analysis checks."""

from devnog.scanner.checks.base import BaseCheck
from devnog.scanner.checks.code_quality import (
    CQ001FunctionLength,
    CQ002DeepNesting,
    CQ003DuplicateCode,
    CQ004UnusedImports,
    CQ005MissingTypeHints,
    CQ006MissingDocstrings,
    CQ007HighComplexity,
    CQ008GlobalMutableState,
    CQ009StarImports,
    CQ010DeadCode,
)
from devnog.scanner.checks.security import (
    SEC001HardcodedSecrets,
    SEC002SQLInjection,
    SEC003MissingRateLimiting,
    SEC004DangerousEval,
    SEC005OpenCORS,
    SEC006DebugTrue,
    SEC007JWTNoExpiry,
    SEC008TokensInURL,
    SEC009WeakHashing,
    SEC010PathTraversal,
    SEC011MissingInputValidation,
    SEC012SubprocessShell,
)
from devnog.scanner.checks.error_handling import (
    ERR001BareExcept,
    ERR002SilentExcept,
    ERR003IOWithoutTry,
    ERR004APIWithoutTry,
    ERR005NoGlobalHandler,
    ERR006AsyncNoCancelHandler,
    ERR007HTTPNoTimeout,
    ERR008ReturnNoneOnError,
)
from devnog.scanner.checks.dependencies import (
    DEP001KnownCVEs,
    DEP002AbandonedPackages,
    DEP003UnpinnedDeps,
    DEP004UnusedDeps,
    DEP005DuplicateFunctionality,
    DEP006OutdatedPackages,
    DEP007MissingRequirements,
    DEP008DevDepsInProd,
)

ALL_CHECKS: list[type[BaseCheck]] = [
    CQ001FunctionLength,
    CQ002DeepNesting,
    CQ003DuplicateCode,
    CQ004UnusedImports,
    CQ005MissingTypeHints,
    CQ006MissingDocstrings,
    CQ007HighComplexity,
    CQ008GlobalMutableState,
    CQ009StarImports,
    CQ010DeadCode,
    SEC001HardcodedSecrets,
    SEC002SQLInjection,
    SEC003MissingRateLimiting,
    SEC004DangerousEval,
    SEC005OpenCORS,
    SEC006DebugTrue,
    SEC007JWTNoExpiry,
    SEC008TokensInURL,
    SEC009WeakHashing,
    SEC010PathTraversal,
    SEC011MissingInputValidation,
    SEC012SubprocessShell,
    ERR001BareExcept,
    ERR002SilentExcept,
    ERR003IOWithoutTry,
    ERR004APIWithoutTry,
    ERR005NoGlobalHandler,
    ERR006AsyncNoCancelHandler,
    ERR007HTTPNoTimeout,
    ERR008ReturnNoneOnError,
    DEP001KnownCVEs,
    DEP002AbandonedPackages,
    DEP003UnpinnedDeps,
    DEP004UnusedDeps,
    DEP005DuplicateFunctionality,
    DEP006OutdatedPackages,
    DEP007MissingRequirements,
    DEP008DevDepsInProd,
]

__all__ = ["BaseCheck", "ALL_CHECKS"]
